# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(max_length=50)),
                ('emp_address', models.CharField(max_length=100, null=True)),
                ('emp_city', models.CharField(max_length=50, null=True)),
                ('emp_state', models.CharField(max_length=50, null=True)),
                ('emp_zip', models.CharField(max_length=20, null=True)),
                ('emp_level', models.CharField(max_length=20)),
                ('emp_notes', models.TextField(null=True)),
            ],
        ),
    ]
