# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('shift_in', models.DateTimeField(auto_now_add=True)),
                ('shift_out', models.DateTimeField()),
                ('shift_notes', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee'),
        ),
    ]
