# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20160528_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
