# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20160530_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_user',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
