# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_auto_20160530_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(max_length=50)),
                ('emp_address', models.CharField(max_length=100, null=True)),
                ('emp_city', models.CharField(max_length=50, null=True)),
                ('emp_state', models.CharField(max_length=50, null=True)),
                ('emp_zip', models.CharField(max_length=20, null=True)),
                ('emp_start_date', models.DateTimeField(null=True)),
                ('emp_level', models.CharField(max_length=20)),
                ('emp_notes', models.TextField(null=True)),
                ('emp_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('shift_in', models.DateTimeField(auto_now_add=True)),
                ('shift_out', models.DateTimeField()),
                ('shift_notes', models.TextField(null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee')),
            ],
        ),
    ]
