# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_employee_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
