# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20160530_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_in', models.DateTimeField(auto_now_add=True)),
                ('shift_out', models.DateTimeField()),
                ('shift_notes', models.TextField(null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee')),
            ],
        ),
    ]
