# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_out',
            field=models.DateTimeField(null=True),
        ),
    ]
