# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20160530_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_in',
            field=models.DateTimeField(),
        ),
    ]
