# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_customer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_desc', models.CharField(max_length=200, null=True)),
                ('prod_type', models.CharField(max_length=100, null=True)),
                ('prod_active', models.NullBooleanField()),
                ('prod_flag', models.CharField(max_length=100, null=True)),
                ('prod_price', models.FloatField(null=True)),
                ('prod_notes', models.TextField(null=True)),
            ],
        ),
    ]
