# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20160610_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('item_notes', models.TextField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Product')),
            ],
        ),
    ]
