# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20160612_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('supplier_part_id', models.CharField(max_length=50, null=True, unique=True)),
                ('internal_part_id', models.CharField(max_length=50, null=True, unique=True)),
                ('sell_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('notes', models.TextField(null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('notes', models.TextField(null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Part')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('phone2', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('exp_time', models.FloatField(null=True)),
                ('required_level', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Production')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
                ('notes', models.TextField(null=True)),
                ('prod_sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Prod_Sch')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Supplier'),
        ),
        migrations.AddField(
            model_name='prod_sch',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.OrderItem'),
        ),
        migrations.AddField(
            model_name='prod_sch',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Production'),
        ),
        migrations.AddField(
            model_name='prod_parts',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Production'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Supplier'),
        ),
    ]
