# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20160615_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
