# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20160615_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(default='type', max_length=150),
            preserve_default=False,
        ),
    ]
