# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20160616_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_internalID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
