# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20160616_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internalID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
