# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_thing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('order', models.IntegerField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prod_parts',
            name='part',
        ),
        migrations.RemoveField(
            model_name='prod_parts',
            name='production',
        ),
        migrations.RemoveField(
            model_name='task',
            name='exp_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='required_level',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Prod_Parts',
        ),
        migrations.AddField(
            model_name='task_part',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task'),
        ),
    ]
