# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20160623_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=150, null=True)),
                ('supplier_part_id', models.CharField(max_length=50, null=True, unique=True)),
                ('internal_part_id', models.CharField(max_length=50, null=True, unique=True)),
                ('sell_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('supplier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Supplier')),
            ],
        ),
    ]
