# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='part',
            field=models.OneToOneField(default=datetime.datetime(2016, 6, 23, 2, 2, 52, 82739, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='portal.Part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_part',
            name='part',
            field=models.OneToOneField(default='name', on_delete=django.db.models.deletion.CASCADE, to='portal.Part'),
            preserve_default=False,
        ),
    ]
