# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20160623_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='part',
        ),
        migrations.RemoveField(
            model_name='task_part',
            name='part',
        ),
    ]
