# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20160623_0212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
