# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_part_production_purchase_purchase_parts_task_task_part_task_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
