# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20160625_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=150, null=True)),
                ('supplier_part_id', models.CharField(max_length=50, null=True, unique=True)),
                ('internal_part_id', models.CharField(max_length=50, null=True, unique=True)),
                ('sell_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('reorder_at', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('phone2', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('detail', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Part')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('order', models.IntegerField()),
                ('detail', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='prod_task',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Production'),
        ),
        migrations.AddField(
            model_name='prod_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Supplier'),
        ),
    ]
