# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_auto_20160625_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(null=True)),
                ('order_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.OrderItem')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Production')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Production')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('sub_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('detail', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Part')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('order', models.IntegerField()),
                ('detail', models.TextField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task')),
            ],
        ),
        migrations.AddField(
            model_name='prod_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task'),
        ),
    ]
