# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20160625_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='prod_sch',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='prod_sch',
            name='production',
        ),
        migrations.RemoveField(
            model_name='prod_task',
            name='production',
        ),
        migrations.RemoveField(
            model_name='prod_task',
            name='task',
        ),
        migrations.RemoveField(
            model_name='production',
            name='part',
        ),
        migrations.RemoveField(
            model_name='task_part',
            name='part',
        ),
        migrations.RemoveField(
            model_name='task_part',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task_step',
            name='task',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Prod_Sch',
        ),
        migrations.DeleteModel(
            name='Prod_Task',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Task_Part',
        ),
        migrations.DeleteModel(
            name='Task_Step',
        ),
    ]
