# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_auto_20160625_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_in', models.DateTimeField()),
                ('shift_out', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Employee')),
            ],
        ),
    ]
