# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_shiftsch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='internal_part_id',
            field=models.CharField(default='hi', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
