# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_auto_20160704_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Supplier'),
        ),
    ]
