# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_auto_20160705_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
